---
- name: Deploy Portainer Agent when this is a designated outpost server
  community.docker.docker_container:
    name: "portainer_agent"
    image: "portainer/agent:{{ portainer_agent_version }}"
    state: started
    detach: true
    restart_policy: always
    published_ports: "9001:9001"
    image_name_mismatch: "recreate"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
  delegate_to: "{{ item }}"
  loop: "{{ groups['outpost'] }}"
