---
# - debug:
#     msg: "{{ lookup('template', 'settings.json.j2') }}"

- name: Configure Portainer settings
  ansible.builtin.uri:
    url: "{{ portainer_endpoint }}/settings"
    method: PUT
    return_content: true
    headers:
      Authorization: "{{ (auth_token.content | from_json).jwt }}"
    body_format: json
    body: "{{ lookup('template', 'settings.json.j2') }}"
    validate_certs: false
  when: configure_settings and not was_already_running
